services:
  backend-app:
    container_name: lms-backend-container
    build:
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend-app:
    container_name: lms-frontend-container
    build:
      context: ../lms-frontend
      args:
        # Use the public URL that the browser will access
        VITE_API_BASE_URL: http://localhost:8080
    ports:
      - "80:80"
    depends_on:
      - backend-app