services:
  backend-app:
    image: theekshananirmal/lms-backend:latest
    container_name: lms-backend-container
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_USER=${SPRING_USER}
      - SPRING_PASSWORD=${SPRING_PASSWORD}
    restart: always

  frontend-app:
    image: theekshananirmal/lms-frontend:latest
    container_name: lms-frontend-container
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend-app